### ISSUE TITLE
Logout: error messages: "KDE Global shortcuts closed unexpectedly"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/plasma-5.2#47]
Details:
Executable: kglobalaccel5 PID: 2142 Signal: Segmentation fault (11)

**Comment by star-buck** [comment]
still happening when logging out and in again

**Comment by davidedmundson** [comment]
Done, in review. https://git.reviewboard.kde.org/r/122019/

**Comment by davidedmundson** [comment]
Merged

**Comment by star-buck** [comment]
still not fixed in KCI 20150116, which package should the fix be udated in?

**Comment by davidedmundson** [comment]
libkf5globalaccel5 (kglobalaccel framework) from the 12th of Jan.

Latest in the kubuntu-ci repos seems to be Version: 5.6.0+git20150109.0059+14.10-0ubuntu0
which is the 9th Jan.

**Comment by star-buck** [comment]
still happening with kci 20150116
libkf5globalaccel5 package is from 20150114, not sure if the patch is included though?

**Comment by davidedmundson** [comment]
It turns out you do have my patch, but there are two crashers in exactly the same place.
(I know this sounds like a feeble excuse, so monsterous explanation below)

There was a generic crash I fixed, and a special oxygen only one; which is why I wasn't finding it when testing.

The reason they're new is that the shutdown was changed so that instead of kglobalaccel being killed before we log out, we just sweep the X server away from under it and kill it that way. It's a bit unexpected from a developer side. There's apparently some complex reason for doing this, but I don't understand it.

Technically speaking this doesn't affect the Plasma 5.2 release yet, only when a frameworks change happens which will be released in Early Feb. Because we use git master of frameworks we're seeing that early (which is good)

bt
#3  <signal handler called>
#4  0x00007f4ef8c15520 in QArrayData::shared_null () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f4ee2e54e32 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/styles/oxygen.so
#6  0x00007f4ee2e54e49 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/styles/oxygen.so
#7  0x00007f4ef8b36647 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f4ef8b2e7f3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f4ef8b2ea19 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f4ef8b7a28b in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f4ef8b2d9d2 in QFactoryLoader::~QFactoryLoader() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f4ef94a9039 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007f4ef81cb6a9 in __run_exit_handlers (status=1, listp=0x7f4ef854f6c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#14 0x00007f4ef81cb6f5 in __GI_exit (status=<optimized out>) at exit.c:104
#15 0x00007f4efae1866e in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#16 0x00007f4ef8b727ba in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f4ef9440d3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007f4ef9446330 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007f4ef8b4203b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007f4ef8b4407b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007f4ef8b98e83 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007f4ef69adc5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f4ef69adf48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f4ef69adffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007f4ef8b9928c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007f4ef8b3f8d2 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007f4ef8b4737c in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x000000000040da39 in main ()
quit

Will fix again shortly.

**Comment by star-buck** [comment]
any idea if you are able to land this fix in upcoming kci for friday (which is like the last kci before 5.2 comes out)?

**Comment by davidedmundson** [comment]
just put it up for review https://git.reviewboard.kde.org/r/122184/

It should make it for Friday..depends how quickly this goes.

**Comment by star-buck** [comment]
do we know it was packaged and shipped in kci?

**Comment by apachelogger** [comment]
seems it was committed on the 21st so yeah, this should be on KCI

**Comment by star-buck** [comment]
@apachelogger: 
please add the exact package name+version, so i can doublecheck on KCI and also see if it is in netrunner ISO when copied over, thanks.

**Comment by apachelogger** [comment]
kde-style-oxygen-qt5	4:5.1.95+git20150123.0003+14.10-0ubuntu0

**Comment by davidedmundson** [comment]
have you seen the problem since?

**Comment by star-buck** [comment]
seems fixed.
